version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    container_name: smia_db
    environment:
      POSTGRES_DB: smia_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: smia_backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://admin:adminpassword@db:5432/smia_db
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0,172.17.22.40,smia.local
      CORS_ALLOWED_ORIGINS: http://localhost:4200,http://127.0.0.1:4200,http://172.17.22.40:4200,http://smia.local:4200
      CORS_ALLOW_ALL_ORIGINS: "True"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: smia_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    restart: unless-stopped

volumes:
  postgres_data: