sonar.projectKey=smia
sonar.sources=.
sonar.host.url=http://localhost:9000
sonar.token=sqa_402344627feef6ed88f871e2a15ad15bf479b8ce
# ESTA LÍNEA ES LA CLAVE:
sonar.exclusions=**/venv/**, **/node_modules/**, **/*.pyc